config/routes.rb
Rails.application.routes.draw do
  # Users routes
  devise_for :users

  # Route to the homepage
  root to: 'offers#home'

  # Route for booked
  get 'booked', to: 'bookings#booked', as: :booked

  # Route for garage
  get 'garage', to: 'offers#garage', as: :garage

  # The routes top 10
  get "offers/top", to: "offers#top", as: :top

  # The rest of the routes
  resources :offers do
    resources :bookings, only: %i[new create edit update]
  end
  resources :bookings, only: %i[destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :offer
  validates :start_date, :end_date, presence: true, uniqueness: true
  scope :overlapping, ->(start_date, end_date) do
    where "((start_date <= ?) and (end_date >= ?))", end_date, start_date
  end
end

app/models/offer.rb
class Offer < ApplicationRecord
  include PgSearch::Model
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many_attached :photos
  validates :price, :long, :lat, :description, presence: true
  validates :price, inclusion: 5..15
  validates :description, length: { minimum: 8 }
  pg_search_scope :search_by_description,
    against: [ :description ],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :offers # Owner of a bike
  has_one_attached :photo
  # Tomorrow morning you should ask a question about all this
  # You should add this if you want to rent your bike
  has_many :bookings # Want to rent a bike
  # You should add this if you want to use the bike
  # has_many :offers, through: :bookings # Want to rent this bike
  validates :first_name, :last_name, presence: true
  validates :first_name, :last_name, length: { minimum: 3 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  # Pundit: white-list approach
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  def user_not_authorized
    flash[:alert] = "Not on my watch"
    redirect_to(root_path)
  end

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: %i[first_name last_name photo])
  end

  private

  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^offers$)|(^bookings$)/
    # devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^bookings$)/
    # Doubts with that regex expression, what does it mean pages?
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  # line below will call #set_booking method before specified actions
  # before_action :set_booking, only: %i[edit update destroy]
  before_action :set_booking, only: %i[destroy]

  def booked
    @bookeds = current_user.bookings
  end

  def new
    @booking = Booking.new # needed to instantiate the form_for
    @offer = Offer.find(params[:offer_id])

  end

  def create
    @booking = Booking.new(booking_params)
    @booking.offer = Offer.find(params[:offer_id])
    @booking.user = current_user
    authorize @booking

    if @booking.save
      redirect_to booked_path
    else
      @offer = Offer.find(params[:offer_id])
      render :new
      # redirect_to new_offer_booking_path(@booking.offer.id)
    end
  end

  # def edit
  # end

  # def update
  #   @booking.update(booking_params)

  #   # no need for app/views/offers/update.html.erb
  #   redirect_to booking_path(@booking)
  # end

  def destroy
    @booking.destroy

    # no need for app/views/offers/destroy.html.erb
    redirect_to offers_path # It should redirect to the list of users bookings
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  # line below will call #set_offer method before specified actions
  skip_before_action :authenticate_user!, only: %i[home index]
  before_action :set_offer, only: %i[show edit update destroy]

  def garage
    @garage = current_user.offers
  end

  def home
  end

  def index
    # @offers = Offer.all
    if params[:query].present?
      @offers = Offer.search_by_description(params[:query])
    else
      @offers = policy_scope(Offer)
    end
  end

  def show
  end

  def new
    @offer = current_user.offers.new # needed to instantiate the form_for
    authorize @offer
  end

  def create
    @offer = current_user.offers.new(offer_params)
    authorize @offer

    if @offer.save
      # redirect_to restaurant_path(@restaurant)
      redirect_to offer_path(@offer)
    else
      render :new
    end
  end

  def edit
  end

  def update
    authorize @offer

    # no need for app/views/offers/update.html.erb
    if @offer.update(offer_params)
      redirect_to offer_path(@offer)
    else
      render :edit
    end
  end

  def destroy
    authorize @offer
    @offer.destroy
    # no need for app/views/offers/destroy.html.erb
    redirect_to offers_path
  end

  def top
    @offers = policy_scope(Offer).order(created_at: :asc).limit(5)
  end

  private

  def offer_params
    params.require(:offer).permit(:description, :lat, :long, :price, photos: [])
  end

  def set_offer
    @offer = Offer.find(params[:id])
    authorize @offer
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/booked.html.erb
<div class="container ">
  <div class="row justify-content-around mt-3">
    <%= link_to 'All Motorcycles', offers_path, class: "btn-new" %>
  </div>
  <h1 class="text-center mt-3 font-weight-bold tex-color">The Motorcycles I Want to Use</h1>
  <div class="cards">
    <% if @bookeds.empty? %>
      <h3>Looks like you don't any booked motorcycles buddy!</h3>
    <% else %>
      <% @bookeds.each do |booked| %>
        <div class="card mb-3">
          <%= image_tag "category-chopper.jpg", class: "card-img-top" %>
          <div class="card-body">
            <h5 class="card-text"><%= booked.offer.description %></h5>
            <h5 class="card-text"><%= booked.start_date %></h5>
            <h5 class="card-text"><%= booked.end_date %></h5>
            <p class="card-text"><%= link_to 'Details', offer_path(booked.offer), class: "btn btn-outline-primary mt-1"%></p>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/bookings/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-12 col-sm-6 bg-white form">
      <h1 class="row justify-content-center pt-1 title">Book this Motorcycle: <%= @offer.description %></h1>
      <%= simple_form_for [@offer, @booking] do |f| %>
        <%= f.input :start_date %>
        <%= f.input :end_date %>
        <div class="row justify-content-around mt-5">
          <%= f.button :submit, class: "btn-up rounded-pill" %>
          <%= link_to 'Motorcycle Details', offer_path(@offer), class: "btn-back rounded-pill" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RentVintageMotorcicles</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="icon" type="image/png" href="https://res.cloudinary.com/alexisgonzalez/image/upload/v1635525801/production/favicon_zbvpye.ico">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <script src="https://unpkg.com/three@0.126.0/build/three.min.js"></script>
    <script src="https://unpkg.com/three@0.126.0/examples/js/loaders/GLTFLoader.js"></script>
  </head>

  <body>
    <%= render "shared/navbar"%>
    <%= yield %>
    <%= render "shared/flashes" %>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/offers/edit.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-12 col-sm-6 bg-white form">
      <h1 class="row justify-content-center pt-1 title">Edit this motorcycle: <strong><%= @offer.description %></strong> </h1>
      <%= simple_form_for(@offer) do |f| %>
        <%= f.input :description %>
        <%= f.input :price %>
        <%= f.input :lat %>
        <%= f.input :long %>
        <%= f.input :photos, as: :file, input_html: { multiple: true } %>
        <div class= "row justify-content-around mt-5">
          <%= f.button :submit, class: "btn-up rounded-pill" %>
          <%= link_to 'Back', offer_path(@offer), class: "btn-back rounded-pill" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/offers/garage.html.erb
<div class="container ">
  <div class="row justify-content-around mt-3">
    <%= link_to 'All Motorcycles', offers_path, class: "btn-back" %>
    <% if policy(Offer).create? %>
      <%= link_to 'Add', new_offer_path, class: "btn-new" %>
    <% end %>
  </div>

  <h1 class="text-center mt-3 font-weight-bold tex-color">My Motorcicles</h1>


  <div class="cards">
    <% if @garage.empty? %>
      <h3>Looks like you don't any motorcycles buddy!</h3>
    <% else %>
      <% @garage.each do |motorcycle| %>
        <%= link_to offer_path(motorcycle), class: "text-decoration-none" do %>
        <div class="card mb-3 index-cards">
          <% if motorcycle.photos.empty? %>
            <%= image_tag "category-chopper.jpg", class: "card-img-top" %>
          <% else %>
            <%= cl_image_tag motorcycle.photos[0].key, class: "card-img-top" %>
          <% end %>
          <div class="card-body">
            <h5 class="card-text text-center font-weight-bold tex-info"><%= motorcycle.description %></h5>
          </div>
        </div>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/offers/home.html.erb
<div style="position: relative">
  <div class="banner">
    <div class="container">
      <h1>Looking for a<strong><em>Vintage</em></strong> <strong><em>Adventure?</em></strong></h1>
      <p>On a beautiful motorcycle</p>
      <%= link_to "Motorcycles", offers_path, class: "btn btn-ghost" %>
    </div>
  </div>
</div>
<div class="container">
  <div class="home-cards">
  <%# <div class="home-cards mt-5 pt-3"> %>
    <%= link_to offers_path(query: "Chopper"), class: "text-decoration-none shadow-purple" do %>
      <div class="one-category">
        Chopper
      </div>
    <% end %>
    <%= link_to offers_path(query: "vespa"), class: "text-decoration-none shadow-purple" do %>
      <div class="second-category">
        Vespa
      </div>
    <% end %>
    <%= link_to top_path, class: "text-decoration-none shadow-purple" do %>
      <div class="third-category">
        Top 5
      </div>
    <% end %>
    <%= link_to offers_path(query: "vespa"), class: "text-decoration-none shadow-purple" do %>
      <div class="four-category">
        Models
      </div>
    <% end %>
    <%= link_to offers_path(query: "vespa"), class: "text-decoration-none" do %>
      <div class="four-category">
        Models
      </div>
    <% end %>
    <%= link_to offers_path(query: "vespa"), class: "text-decoration-none" do %>
      <div class="four-category">
        Models
      </div>
    <% end %>
    <%= link_to offers_path(query: "vespa"), class: "text-decoration-none" do %>
      <div class="four-category">
        Models
      </div>
    <% end %>
    <%= link_to offers_path(query: "vespa"), class: "text-decoration-none" do %>
      <div class="four-category">
        Models
      </div>
    <% end %>
  </div>
</div>

app/views/offers/index.html.erb
<div class="container ">
  <div class="row justify-content-center mt-4">
    <%= form_tag offers_path, method: :get do %>
      <div class="d-flex">
        <%= text_field_tag :query,
          params[:query],
          class: "form-control",
          placeholder: "Find a Motorcycle"
        %>
        <%= submit_tag "Search", class: "btn-new mx-2" %>
      </div>
    <% end %>
  </div>

  <div class="row justify-content-around mt-4">
    <%= link_to 'Back', root_path, class: "btn-back" %>
    <%= link_to 'New Motorcycle', new_offer_path, class: "btn-new" %>
  </div>

  <h1 class="text-center mt-3 font-weight-bold tex-color">Available Motorcicles</h1>

  <% if @offers.empty? %>
    <h1 class="row justify-content-around">Looks like we didn't find your Motorcycle mate, sorry 😥</h1>
  <% end %>

  <div class="cards">
    <% @offers.each do |offer| %>
      <%= link_to offer_path(offer), class: "text-decoration-none" do %>
        <div class="card mb-3 index-cards">
          <% if offer.photos.empty? %>
            <%= image_tag "category-chopper.jpg", class: "card-img-top" %>
          <% else %>
            <%= cl_image_tag offer.photos[0].key, class: "card-img-top" %>
          <% end %>
          <div class="card-body">
            <h5 class="card-text text-center font-weight-bold tex-info"><%= offer.description %></h5>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/offers/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-12 col-sm-6 bg-white form">
      <h1 class="row justify-content-center pt-1 title font-weight-bold">Add a New Motorcycle</h1>
        <%= simple_form_for(@offer) do |f| %>
          <%= f.input :description %>
          <%= f.input :price %>
          <%= f.input :lat %>
          <%= f.input :long %>
          <%= f.input :photos, as: :file, input_html: { multiple: true } %>
          <div class= "row justify-content-around mt-5">
            <%= f.button :submit, class: "btn-up  rounded-pill" %>
            <%= link_to 'Back', offers_path, class: "btn-back rounded-pill" %>
          </div>
      <% end %>
    </div>
  </div>
</div>

app/views/offers/show.html.erb
<div class="container">
  <div class="row justify-content-around mt-3 mb-3">
    <%= link_to 'Back', offers_path, class: "btn-back" %>
    <% if current_user != @offer.user %>
      <%= link_to 'Book', new_offer_booking_path(@offer),class: "btn-book" %>
    <% end %>
    <% if policy(@offer).edit? %>
      <%= link_to 'Edit', edit_offer_path(@offer), class: "btn-edit" %>
    <% end %>
    <% if policy(@offer).destroy?%>
      <%= link_to 'Remove', offer_path(@offer), method: :delete, data: { confirm: "Are you sure" }, class: "btn-remove" %>
    <% end %>
  </div>

  <h1 class="text-center mt-1 mb-3 font-weight-bold tex-color">Your Dream Bike</h1>

  <div id="carouselExampleIndicators" class="carousel slide shadow-slider" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
      <% if @offer.photos.empty? %>
        <div class="carousel-item active">
          <%= image_tag "category-chopper.jpg", class: "d-block w-100" %>
        </div>
        <div class="carousel-item">
          <%= image_tag "category-chopper.jpg", class: "d-block w-100" %>
        </div>
        <div class="carousel-item">
          <%= image_tag "category-chopper.jpg", class: "d-block w-100" %>
        </div>
      <% else %>
        <% @offer.photos.each_with_index do |photo, index| %>
          <% if index == 0 %>
            <div class="carousel-item active">
              <%= cl_image_tag photo.key, class: "d-block w-100" %>
            </div>
          <% else %>
            <div class="carousel-item">
              <%= cl_image_tag photo.key, class: "d-block w-100" %>
            </div>
          <% end %>
        <% end %>
      <% end %>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>

  <div class="d-flex">
    <div class="col-4 p-0">
      <div class="mt-3 p-3 mb-5 rounded tex-descr" style="max-width: 18rem;">
        <div class="card-header text-uppercase font-weight-bold">Description</div>
        <div class="card-body">
          <p class="card-text"><%= @offer.description %></p>
        </div>
      </div>

      <div class="mt-3 p-3 mb-5 rounded tex-price" style="max-width: 18rem;">
        <div class="card-header text-uppercase font-weight-bold">Price</div>
        <div class="card-body">
          <h5 class="card-title"><%= @offer.price %></h5>
        </div>
      </div>

      <div class="mt-3 p-3 mb-5 rounded tex-loca" style="max-width: 18rem;">
        <div class="card-header text-uppercase font-weight-bold">Location</div>
        <div class="card-body">
          <p class="card-text"><%= @offer.lat %> <%= @offer.long %></p>
        </div>
      </div>

    </div> <!-- info -->
    <div id="map"
         class="shadow-map col-8 mt-3 mb-5 rounded"
         data-lat="<%= @offer.lat %>"
         data-long="<%= @offer.long %>"
         data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div><!--container -->

</div>

app/views/offers/top.html.erb
<div class="container ">
  <div class="row justify-content-around mt-4">
    <%= link_to 'Back', root_path, class: "btn-back" %>
    <!-- <%= link_to 'New Motorcycle', new_offer_path, class: "btn-new" %> -->
  </div>

  <h1 class="text-center mt-3 font-weight-bold tex-color">Top 5</h1>

  <div class="cards">
    <% @offers.each do |offer| %>
      <%= link_to offer_path(offer), class: "text-decoration-none" do %>
        <div class="card mb-3 index-cards">
          <% if offer.photos.empty? %>
            <%= image_tag "category-chopper.jpg", class: "card-img-top" %>
          <% else %>
            <%= cl_image_tag offer.photos[0].key, class: "card-img-top" %>
          <% end %>
          <div class="card-body">
            <h5 class="card-text text-center font-weight-bold tex-info"><%= offer.description %></h5>
          </div>
        </div>
      <% end %> <!-- link_to etails -->
    <% end %> <!-- @ffers.each -->
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    Get to your destination faster with <em>US</em>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div id="<%= "navbar-home" if current_page?(root_url) %>" class="navbar navbar-expand-sm navbar-light fixed-top navbar-color">
  <%= link_to root_path, class: "logo-home" do%>
    <i class="fas fa-smog"></i>
    <i class="fas fa-motorcycle"></i>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item mx-2">
          <%= link_to "Rent your bike", new_offer_path, class: "nav-link text-color" %>
        </li>
        <li class="nav-item mx-2">
          <%= link_to "See all bikes", offers_path, class: "nav-link text-color" %>
        </li>
        <li class="nav-item dropdown mx-2">
          <% if current_user.photo.attached? %>
            <%= cl_image_tag current_user.photo.key, crop: :fit, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% else %>
            <%= image_tag "hc1.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "My Bookings", booked_path, class: "dropdown-item btn-drop" %>
            <%= link_to "My Garage", garage_path, class: "dropdown-item btn-drop" %>
            <%= link_to "Log Out", destroy_user_session_path, class: "dropdown-item btn-drop" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link text-color" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>